# -*- coding: utf-8 -*-
"""PHASE1-TITANIC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z260ceVAGe8_Tha5Tp46dF85JZTjkRAX
"""

'''PHASE 1 — TITANIC DATA CLEANING'''

#import the tools that will help us read and work with the our data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

'''step 1: Load the dataset'''


#We load the Titanic dataset so we can start exploring it
df = pd.read_csv("/content/sample_data/train.csv")

#We look at the first 5 rows to understand what kind of information we have
print(df.head(5))

'''step 2: Check dataset size'''


#This shows how many passengers (rows) and how many details (columns) we have
print(df.shape)

'''step 3: Look at column types and missing values'''


#This helps us see what kind of data each column contains...and if there are any missing values that need fixing
print(df.info())

'''step 4 Fix column types'''

#Some columns look like numbers, but they actually represent groups.
#For example, passenger class (1, 2, 3) is not a number we calculate with,
#it simply shows which group the passenger belongs to. So we change these columns to categorize to reflect their real meaning.

df["Pclass"] = df["Pclass"].astype("category")
df["Survived"] = df["Survived"].astype("category")
df["Sex"] = df["Sex"].astype("category")
df["Embarked"] = df["Embarked"].astype("category")

'''step 5: Check missing values'''


#Here we count how many missing values exist in each column.
#This helps us decide what needs to be cleaned.
print (df.isnull().sum())

'''step 6 : handle missing values'''


#The Cabin column has too many missing values.
#Since most of the information is missing, we cannot confidently guess or fill it.
#So we remove this column to keep the data reliable.


#Some passengers are missing their age.
#Instead of guessing randomly, we fill missing ages. with the middle value (median).
#We choose the middle value because it is not affected, by very young or very old passengers.
df["Age"] = df["Age"].fillna(df["Age"].median())
print(df)
#A few passengers are missing their port of embarkation.
#Since only a small number is missing, we fill them with the most common port in the dataset.
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
print(df)

'''step 7: Check for duplicates'''

#We check if there are any repeated passengers in the dataset.
#Duplicates could affect our results.
print (df.duplicated().sum())

#If duplicates exist, we remove them to keep each passenger unique.
df = df.drop_duplicates()

'''step 8: Check target column for extreme values'''


#The target column (Survived) only has two values: 0 and 1.
#this means there are no extreme values to fix.
sns.boxplot(x="Survived", data=df)
plt.title("Survival Count")
plt.show()

#or we also can use count plot for more clear results

sns.countplot(x="Survived", data=df)
plt.title("Survival Count")
plt.show()

'''''step 9: Create cleaning function (pipline)'''''


#Now we create a function that repeats all cleaning steps.
#This makes our work organized and easy to reuse later.

def clean_data(df):
    df = df.copy()

    df["Pclass"] = df["Pclass"].astype("category")
    df["Survived"] = df["Survived"].astype("category")
    df["Sex"] = df["Sex"].astype("category")
    df["Embarked"] = df["Embarked"].astype("category")

    df = df.drop(columns=["Cabin"])

    df["Age"] = df["Age"].fillna(df["Age"].median())
    df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

    df = df.drop_duplicates()

    return df

''' step 10: Apply the function'''


#We apply the cleaning function to make sure everything works correctly
df = clean_data(df)
print(df)

'''step 11: Final checks'''


#These checks confirm that cleaning worked properly.

#Make sure there are no missing ages left
assert df["Age"].isnull().sum() == 0

#Make sure there are no missing embarkation values
assert df["Embarked"].isnull().sum() == 0

#Make sure the Cabin column was successfully removed
assert "Cabin" not in df.columns

'''PHASE 1 — TITANIC DATA CLEANING...COMPLETED'''